### ISSUE TITLE
Doesn't Seem To Work with Memcached?

### ISSUE THREAD

**Issue by jamescarr** [kontera-technologies/nutcracker-web#5]
We use nutcracker for proxying both redis and twemproxy. This does not seem to report on memcached backends.

**Comment by brijesh27** [comment]
Hi Eranb,

Could you please help me in nutcracker-web, with nutcracker-web option i am not able to run proxy in debug mode and not able to log the twemproxy log , so could you help me how can i log  twemproxy logging with nutcracker-web option and one more thing is there any way to flush all data of stats port 22222 so i can get data of 15 mins or run time data instead of whole data/errors when last twemproxy was restarted.

**Comment by eranb** [comment]
@brijesh27 see #6
